// src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import Dashboard from './components/Dashboard.vue';
import Theater from './components/Theater.vue';
import type { Program } from './types';

type View = 'dashboard' | 'theater';

interface ActiveSession {
  program: Program;
  subjectId: string;
}

const view = ref<View>('dashboard');
const activeSession = ref<ActiveSession | null>(null);

const startSession = (program: Program, subjectId: string) => {
  activeSession.value = { program, subjectId };
  view.value = 'theater';
};

const endSession = () => {
  activeSession.value = null;
  view.value = 'dashboard';
};
</script>

<template>
  <div class="w-full h-screen bg-black text-white overflow-hidden">
    <Dashboard v-if="view === 'dashboard'" @startSession="startSession" />
    
    <Theater 
      v-if="view === 'theater' && activeSession"
      :program="activeSession.program" 
      :subjectId="activeSession.subjectId"
      @exit="endSession"
    />
  </div>
</template>

<style scoped>
/* No specific scoped styles needed, using Tailwind */
</style>

// archive/react-version/App.tsx
import React, { useState } from 'react';
import { Dashboard } from './components/Dashboard';
import { Theater } from './components/Theater';
import { Program } from './types';

type View = 'dashboard' | 'theater';

interface ActiveSession {
  program: Program;
  subjectId: string;
}

const App: React.FC = () => {
  const [view, setView] = useState<View>('dashboard');
  const [activeSession, setActiveSession] = useState<ActiveSession | null>(null);

  const startSession = (program: Program, subjectId: string) => {
    setActiveSession({ program, subjectId });
    setView('theater');
  };

  const endSession = () => {
    setActiveSession(null);
    setView('dashboard');
  };

  return (
    <div className="w-full h-screen bg-black text-white overflow-hidden">
      {view === 'dashboard' && (
        <Dashboard onStartSession={startSession} />
      )}
      
      {view === 'theater' && activeSession && (
        <Theater 
          program={activeSession.program} 
          subjectId={activeSession.subjectId}
          onExit={endSession}
        />
      )}
    </div>
  );
};

export default App;
